name: electrostore
recipe: lamp
config:
  php: '8.1'
  webroot: /web
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  database:
    creds:
      user: electrostore
      password: electrostore
      database: electrostore